# Generated by Django 2.2.5 on 2019-09-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
